### ISSUE TITLE
universal cli tool

### ISSUE THREAD

**Issue by ggagnidze** [OOPS-ORG-PHP/mod_screwim#21]
Can you make universal clii tool, which will ask for keybyte for decode and encode? So we can use one binary for all installations/customers?

If -k is not passed, then keybyte should be asked, so keybyte will not goes to .bash_history

**Comment by Joungkyun** [comment]
In November 2017, [php_screwhook](https://github.com/jc-lab/) has been introduced that hooks up the zend_compile_file API before mod_screwim to take an encrypted file. To prevent this module, the values of SCREWIM and SCREWIM_LEN must be changed, and longer is better.

Since the universal cli tool has the same meta data, using an universal cli tool increases the risk.
